### ISSUE TITLE
dog-years subject

### ISSUE THREAD

**Issue by healingdrawing** [01-edu/public#1705]
dog-years
---
```
function dogYears(planet, age) {
  orbitalPeriod = {
    earth: 1.0,
    mercury: 0.2408467,
    venus: 0.61519726,
    mars: 1.8808158,
    jupiter: 11.862615,
    saturn: 29.447498,
    uranus: 84.016846,
    neptune: 164.79132
  }
  dogAge = age / (orbitalPeriod[planet] * 31557600) * 7;
  return dogAge.toFixed(2);
}
```
error:
```
test #1 failed:
({ eq }) => eq(dogYears('earth', 1000000000), 221.82)

ReferenceError: orbitalPeriod is not defined
    at dogYears (file://dog-years.js:4:17)
    at file://dog-years.js:36:18
    at runTests (file:///app/test.mjs:179:9)
```
in same time it works in javascript playground. So, this is fail from the platform side

<img width="1316" alt="Screenshot 2023-01-09 at 15 45 46" src="https://user-images.githubusercontent.com/39751647/211322444-5f1a2c4d-f853-4c14-8819-5697fbfde9bf.png">

**Comment by davhojt** [comment]
@healingdrawing You have something to fix with your code. Keep trying, and good luck 😊.
