### ISSUE TITLE
listclear subject

### ISSUE THREAD

**Issue by pbgo2** [01-edu/public#991]
listclear
---panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x487be1]

goroutine 1 [running]:
student.ListClear(...)
	/jail/piscine-go/listclear.go:19
main.main()
	/jail/go-tests/tests/listclear_test/main.go:43 +0x2e1
exit status 2

unexpected violation error when attempt to clear linked list. This issue not appear for code when tested in IDE , seems test function bug

**Comment by MSilva95** [comment]
Hello @pbgo2!
The problem is in your solution, basically is doing this to the list:
```
1 -> nil
1  -> nil
nil  -> nil
nil -> nil
nil
```
it is very messy...
Try to run your solution with the list empty like so :

```
func main() {
	link := &List{}

	// ListPushBack(link, "I")
	// ListPushBack(link, 1)
	// ListPushBack(link, "something")
	// ListPushBack(link, 2)

	fmt.Println("------list------")
	PrintList(link)
	ListClear(link)
	fmt.Println("------updated list------")
	PrintList(link)
}
```

**Comment by pbgo2** [comment]
Hi thank you for your feedback.
Yes I fix issue in my code and now all is fine.
Staying in touch
Peter
